version: '3'

services:
  webserver:
    build: ./
    volumes:
      - ./cmake-build-debug/:/usr/local/apache2/htdocs/
      - ./:/usr/source/
  #  links:
  #    - postgres-database
    ports:
     - '80:80'
     - '443:443'

  #postgres-database:
  #  image: postgres:latest
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: 1234
